' PlantUML Use Case diagram template for DiagramaUC_TPI.puml
@startuml DiagramaUC_TPI
left to right direction
skinparam usecase {
    BackgroundColor PaleGreen
    BorderColor DarkGreen
}

title Diagrama de Casos de Uso - Estacionamiento UTN

actor "Administrador" as Usuario
rectangle "Sistema de gestion de usuarios y vehiculos" {
    usecase "Registrar Vehiculo" as UC_Vehiculo
    usecase "Registrar Cuenta Usuario" as UC_Registrar
    usecase "Recargar Saldo" as UC_Recargar
    usecase "Registrar abono" as UC_Abono
}
actor "Encargado E/S" as ErT
rectangle "Sistema de ingreso/egreso"{
    usecase "Registrar Ingreso" as UC_Ingreso
    usecase "Registrar Egreso" as UC_Egreso
    usecase "Generar y Emitir Informe" as UC_GenerarInforme
    usecase "Registar Cobro" as UC_Cobro
}
ErT --> UC_Ingreso
ErT --> UC_Egreso
ErT --> UC_GenerarInforme
ErT --> UC_Cobro

actor "UTN" as UTN 

Usuario --> UC_Vehiculo
Usuario --> UC_Registrar 
Usuario --> UC_Abono
Usuario --> UC_Recargar
UC_Registrar --> UTN

@enduml